from PIL import Image, ImageDraw, ImageFont, ImageFilter, ImageOps
from io import BytesIO
import textwrap
from image_gen import download_image, get_star_rating
import os

FONT_BOLD = os.path.join("fonts", "DejaVuSans-Bold.ttf")
FONT_REG = os.path.join("fonts", "DejaVuSans.ttf")

# ---------- Helper ----------
def add_branding(draw, canvas, x, y, branding_img=None):
    if branding_img:
        logo = branding_img.resize((70, 70))
        canvas.paste(logo, (x, y), logo)
        draw.text((x + 80, y + 25), "KENSHIN ANIME", font=ImageFont.truetype(FONT_BOLD, 28), fill=(255,255,255))
    else:
        draw.text((x, y + 25), "⚡ KENSHIN ANIME", font=ImageFont.truetype(FONT_BOLD, 28), fill=(255,255,215))

# Style 1: Classic Card (Left poster, right details)
async def style_classic(info, branding_img=None):
    canvas = Image.new("RGBA", (1080, 1350), (10,10,20,255))
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 48)
    desc_font = ImageFont.truetype(FONT_BOLD, 28)
    genre_font = ImageFont.truetype(FONT_BOLD, 24)
    rating_font = ImageFont.truetype(FONT_BOLD, 32)

    # Header
    header = Image.new("RGBA", (1080, 100), (0,0,0,180))
    canvas.paste(header, (0,0))
    add_branding(draw, canvas, 30, 10, branding_img)

    # Poster
    poster = await download_image(info["cover"])
    poster = poster.resize((500, 700), Image.LANCZOS)
    canvas.paste(poster, (50, 130), poster)

    # Right details
    xr, yr = 600, 150
    title = info["title"][:40]
    draw.text((xr, yr), title, font=title_font, fill=(255,255,255))
    yr += 70
    stars = get_star_rating(info["rating"])
    draw.text((xr, yr), f"{stars}  {info['rating']:.1f}/10", font=rating_font, fill=(255,215,0))
    yr += 60
    genres = " • ".join(info["genres"])
    draw.text((xr, yr), genres, font=genre_font, fill=(200,200,200))
    yr += 50
    synopsis = info["synopsis"]
    lines = textwrap.wrap(synopsis, width=50)
    for line in lines[:6]:
        draw.text((xr, yr), line, font=desc_font, fill=(220,220,220))
        yr += 35

    # Footer
    footer = Image.new("RGBA", (1080, 80), (0,0,0,200))
    canvas.paste(footer, (0,1270))
    draw.text((30, 1285), "✨ Generated by KENSHIN ANIME Bot", font=genre_font, fill=(150,150,150))
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 2: Full Bleed (Blur background, centered)
async def style_full_bleed(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (0,0,0,255))
    bg = await download_image(info["cover"])
    bg = bg.resize((1080,1350), Image.LANCZOS).filter(ImageFilter.GaussianBlur(20))
    canvas.paste(bg, (0,0))
    overlay = Image.new("RGBA", (1080,1350), (0,0,0,160))
    canvas.paste(overlay, (0,0), overlay)
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 64)
    desc_font = ImageFont.truetype(FONT_BOLD, 30)
    genre_font = ImageFont.truetype(FONT_BOLD, 28)

    draw.text((540, 300), info["title"][:40], font=title_font, fill=(255,255,255), anchor="mm")
    stars = get_star_rating(info["rating"])
    draw.text((540, 450), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,215,0), anchor="mm")
    genres = " • ".join(info["genres"])
    draw.text((540, 550), genres, font=genre_font, fill=(255,255,255), anchor="mm")
    synopsis = info["synopsis"]
    lines = textwrap.wrap(synopsis, width=50)
    y = 700
    for line in lines[:5]:
        draw.text((540, y), line, font=desc_font, fill=(220,220,220), anchor="mm")
        y += 40
    add_branding(draw, canvas, 470, 1220, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 3: Modern Card (Top poster, bottom details)
async def style_modern(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (15,15,25,255))
    poster = await download_image(info["cover"])
    poster = poster.resize((1080,600), Image.LANCZOS)
    canvas.paste(poster, (0,0))
    overlay = Image.new("RGBA", (1080,600), (0,0,0,100))
    canvas.paste(overlay, (0,0), overlay)
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 54)
    desc_font = ImageFont.truetype(FONT_BOLD, 32)
    genre_font = ImageFont.truetype(FONT_BOLD, 28)

    draw.text((50, 620), info["title"][:40], font=title_font, fill=(255,255,255))
    stars = get_star_rating(info["rating"])
    draw.text((50, 700), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,215,0))
    genres = " • ".join(info["genres"])
    draw.text((50, 780), genres, font=genre_font, fill=(200,200,200))
    synopsis = info["synopsis"]
    lines = textwrap.wrap(synopsis, width=55)
    y = 870
    for line in lines[:5]:
        draw.text((50, y), line, font=desc_font, fill=(220,220,220))
        y += 40
    add_branding(draw, canvas, 50, 1280, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 4: Minimalist (Right poster, left text, clean)
async def style_minimal(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (20,20,35,255))
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 58)
    desc_font = ImageFont.truetype(FONT_BOLD, 30)
    genre_font = ImageFont.truetype(FONT_BOLD, 26)

    # Poster on right
    poster = await download_image(info["cover"])
    poster = poster.resize((500, 700), Image.LANCZOS)
    canvas.paste(poster, (550, 300), poster)

    # Left side text
    draw.text((60, 300), info["title"][:40], font=title_font, fill=(255,255,255))
    stars = get_star_rating(info["rating"])
    draw.text((60, 400), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,215,0))
    genres = " • ".join(info["genres"])
    draw.text((60, 480), genres, font=genre_font, fill=(200,200,200))
    synopsis = info["synopsis"]
    lines = textwrap.wrap(synopsis, width=45)
    y = 580
    for line in lines[:6]:
        draw.text((60, y), line, font=desc_font, fill=(220,220,220))
        y += 38
    add_branding(draw, canvas, 60, 1240, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 5: Poster Focus (Large cover, overlay, title bottom)
async def style_poster_focus(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (0,0,0,255))
    poster = await download_image(info["cover"])
    poster = poster.resize((1080,1350), Image.LANCZOS)
    canvas.paste(poster, (0,0))
    overlay = Image.new("RGBA", (1080,1350), (0,0,0,140))
    canvas.paste(overlay, (0,0), overlay)
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 64)
    desc_font = ImageFont.truetype(FONT_BOLD, 32)
    genre_font = ImageFont.truetype(FONT_BOLD, 28)

    # Title at bottom
    draw.text((540, 1050), info["title"][:40], font=title_font, fill=(255,255,255), anchor="mm")
    stars = get_star_rating(info["rating"])
    draw.text((540, 1130), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,215,0), anchor="mm")
    genres = " • ".join(info["genres"])
    draw.text((540, 1200), genres, font=genre_font, fill=(255,255,255), anchor="mm")
    add_branding(draw, canvas, 470, 1270, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 6: Magazine (Left poster with gradient, title over image)
async def style_magazine(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (10,10,25,255))
    poster = await download_image(info["cover"])
    poster = poster.resize((600, 900), Image.LANCZOS)
    canvas.paste(poster, (40, 200))
    # Add a shadow/glow
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 52)
    desc_font = ImageFont.truetype(FONT_BOLD, 28)
    genre_font = ImageFont.truetype(FONT_BOLD, 24)

    # Title overlapping poster
    draw.text((40, 190), info["title"][:40], font=title_font, fill=(255,255,255))
    stars = get_star_rating(info["rating"])
    draw.text((40, 270), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,215,0))

    # Right side details
    xr = 700
    yr = 200
    genres = " • ".join(info["genres"])
    draw.text((xr, yr), genres, font=genre_font, fill=(200,200,200))
    yr += 50
    synopsis = info["synopsis"]
    lines = textwrap.wrap(synopsis, width=35)
    for line in lines[:7]:
        draw.text((xr, yr), line, font=desc_font, fill=(220,220,220))
        yr += 35
    add_branding(draw, canvas, 700, 1150, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 7: Vertical Banner (Poster top, text stacked)
async def style_vertical(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (0,0,0,255))
    poster = await download_image(info["cover"])
    poster = poster.resize((1080,600), Image.LANCZOS)
    canvas.paste(poster, (0,0))
    # Gradient overlay at bottom
    gradient = Image.new("RGBA", (1080,750), (0,0,0,200))
    canvas.paste(gradient, (0,600), gradient)
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 56)
    desc_font = ImageFont.truetype(FONT_BOLD, 30)
    genre_font = ImageFont.truetype(FONT_BOLD, 26)

    draw.text((540, 640), info["title"][:40], font=title_font, fill=(255,255,255), anchor="mm")
    stars = get_star_rating(info["rating"])
    draw.text((540, 720), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,215,0), anchor="mm")
    genres = " • ".join(info["genres"])
    draw.text((540, 800), genres, font=genre_font, fill=(255,255,255), anchor="mm")
    synopsis = info["synopsis"]
    lines = textwrap.wrap(synopsis, width=55)
    y = 900
    for line in lines[:4]:
        draw.text((540, y), line, font=desc_font, fill=(220,220,220), anchor="mm")
        y += 40
    add_branding(draw, canvas, 470, 1200, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 8: Dark Gradient (Inspired by Chronicles of the Demon Faction)
async def style_dark_gradient(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (5,5,15,255))
    # Create gradient
    for i in range(1350):
        color = int(10 + i / 1350 * 20)
        ImageDraw.Draw(canvas).rectangle([0,i,1080,i+1], fill=(color,color,color+10))
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 56)
    desc_font = ImageFont.truetype(FONT_BOLD, 30)
    genre_font = ImageFont.truetype(FONT_BOLD, 26)

    # Poster on left, inset
    poster = await download_image(info["cover"])
    poster = poster.resize((450, 650), Image.LANCZOS)
    canvas.paste(poster, (50, 200), poster)
    # White border
    draw.rectangle([45,195,505,855], outline=(255,255,255), width=3)

    xr = 550
    yr = 220
    draw.text((xr, yr), info["title"][:40], font=title_font, fill=(255,255,255))
    yr += 70
    stars = get_star_rating(info["rating"])
    draw.text((xr, yr), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,215,0))
    yr += 60
    genres = " • ".join(info["genres"])
    draw.text((xr, yr), genres, font=genre_font, fill=(200,200,200))
    yr += 50
    synopsis = info["synopsis"]
    lines = textwrap.wrap(synopsis, width=40)
    for line in lines[:5]:
        draw.text((xr, yr), line, font=desc_font, fill=(220,220,220))
        yr += 35
    add_branding(draw, canvas, 550, 1150, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 9: Anime List (Like Manhwa Weebs card)
async def style_anime_list(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (25,25,35,255))
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 52)
    desc_font = ImageFont.truetype(FONT_BOLD, 28)
    genre_font = ImageFont.truetype(FONT_BOLD, 24)

    # Poster as background with semi-transparent overlay
    bg = await download_image(info["cover"])
    bg = bg.resize((1080,1350), Image.LANCZOS)
    canvas.paste(bg, (0,0))
    overlay = Image.new("RGBA", (1080,1350), (0,0,0,170))
    canvas.paste(overlay, (0,0), overlay)

    # Card-like box
    card = Image.new("RGBA", (950, 800), (0,0,0,200))
    canvas.paste(card, (65, 275), card)

    draw.text((540, 320), info["title"][:40], font=title_font, fill=(255,255,255), anchor="mm")
    stars = get_star_rating(info["rating"])
    draw.text((540, 410), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,215,0), anchor="mm")
    genres = " • ".join(info["genres"])
    draw.text((540, 490), genres, font=genre_font, fill=(255,255,255), anchor="mm")
    synopsis = info["synopsis"]
    lines = textwrap.wrap(synopsis, width=55)
    y = 580
    for line in lines[:5]:
        draw.text((540, y), line, font=desc_font, fill=(220,220,220), anchor="mm")
        y += 40
    add_branding(draw, canvas, 470, 1100, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out

# Style 10: Kenshin Special (Diagonal stripes, vibrant)
async def style_kenshin_special(info, branding_img=None):
    canvas = Image.new("RGBA", (1080,1350), (255, 80, 40, 255))  # Vibrant red-orange
    draw = ImageDraw.Draw(canvas)

    # Diagonal white stripes
    for i in range(-1350, 1350, 80):
        draw.line([(i,0), (i+1350,1350)], fill=(255,255,255,100), width=15)
    # Poster clipped in circle
    poster = await download_image(info["cover"])
    poster = poster.resize((600, 600), Image.LANCZOS)
    mask = Image.new("L", (600,600), 0)
    mask_draw = ImageDraw.Draw(mask)
    mask_draw.ellipse((0,0,600,600), fill=255)
    canvas.paste(poster, (240, 200), mask)

    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 64)
    desc_font = ImageFont.truetype(FONT_BOLD, 32)
    genre_font = ImageFont.truetype(FONT_BOLD, 28)

    draw.text((540, 850), info["title"][:40], font=title_font, fill=(255,255,255), anchor="mm")
    stars = get_star_rating(info["rating"])
    draw.text((540, 940), f"{stars}  {info['rating']:.1f}/10", font=desc_font, fill=(255,255,0), anchor="mm")
    genres = " • ".join(info["genres"])
    draw.text((540, 1010), genres, font=genre_font, fill=(255,255,255), anchor="mm")
    add_branding(draw, canvas, 470, 1200, branding_img)
    out = BytesIO()
    canvas.save(out, format="PNG")
    out.seek(0)
    return out
